### ISSUE TITLE
Copying of sheets from standard form does not work

### ISSUE THREAD

**Issue by mariobehling** [fossasia/ots15-companion#1]
copying of sheet to the app spreadsheet results in crash of app. I see a few fields are changed and I had a quick look if I could fix that, but did not work.

**Comment by championswimmer** [comment]
Sorry for a bit of confusion on my end, but are we using
https://github.com/fossasia/fossasia-companion-android/tree/opentech

or

https://github.com/fossasia/ots15-companion

for the OpenTechSummit 15 ?

# 

  Arnav Gupta (championswimmer)
  LinkedIn http://in.linkedin.com/in/arnavgupta/ | Web
http://championswimmer.in | Blog http://blog.championswimmer.in |
Twitter http://twitter.com/championswimmer | Facebook
http://facebook.com/championswimmer | Github
http://github.com/championswimmer

**Comment by mariobehling** [comment]
Good question. Let's keep things clean and separate. We use: https://github.com/fossasia/ots15-companion

**Comment by mariobehling** [comment]
@mananwason Please delete the branch https://github.com/fossasia/fossasia-companion-android/tree/opentech

**Comment by mananwason** [comment]
Done @mariobehling

**Comment by mariobehling** [comment]
In the test app, I don't see the content of the sheets in the app, e.g. from OpenTech 1 track.

**Comment by mananwason** [comment]
That has not been inserted yet. I'm on it.

**Comment by mariobehling** [comment]
How do you plan to do it? It was already implemented in the FOSSASIA companion. I guess @batraabhishek tried to improve the way, it is done.

**Comment by mananwason** [comment]
It depends on the fields we want to keep within a track. Can you specify that?

**Comment by mariobehling** [comment]
I dont understand the question. Please look exactly at the FOSSASIA companion app and the spreadsheet of that app.

**Comment by mananwason** [comment]
I did see that but I was exploring other possibilities

**Comment by batraabhishek** [comment]
@mananwason Hi...whats the status here... I can look into this, if it is still not fixed. :) Thanks and sorry for the long absence. :)

**Comment by mariobehling** [comment]
We talked a few hours ago. We need some pointers to make it work again. Maybe some structure of the sheet is different or the date is the blocker.

**Comment by mariobehling** [comment]
The struture of the OpenTech sheet is different to the FOSSASIA app sheet. I guess here is an error to. Please compare with the sheet I copied into the spreadsheet.

**Comment by mananwason** [comment]
@mariobehling This has been done in my latest commit with some other changes as well. @championswimmer How can I use travis to check if everything is fine?

**Comment by mananwason** [comment]
@mariobehling Should we close this ?
