### ISSUE TITLE
Dates displayed in app are March 14 etc. - change to May 14

### ISSUE THREAD

**Issue by mariobehling** [fossasia/ots15-companion#2]
Is there a way to extract the dates from the info in the spreadsheet maybe?
Alternatively hardcode it for the moment.

**Comment by mananwason** [comment]
Done !!

**Comment by mariobehling** [comment]
The event is "ONLY" on May 14. Please change it.

**Comment by mananwason** [comment]
Done in my latest commit
![screenshot8620404369571782418](https://cloud.githubusercontent.com/assets/10570249/7491305/e546bb24-f405-11e4-882b-3eeaa42855d7.png)

**Comment by mananwason** [comment]
Sorry wrong screen
![screenshot8845188303963887860](https://cloud.githubusercontent.com/assets/10570249/7491328/297841c8-f406-11e4-979f-3fd887f22941.png)
