### ISSUE TITLE
Several fields displayed in overview and detailed views are not correct

### ISSUE THREAD

**Issue by mariobehling** [fossasia/ots15-companion#5]
Please compare with FOSSASIA companion.
We want to display the following fields:
1. Title of talk
2. Given Name, Family Name
3. Organization
eg. 
<b>Free Wireless Networks in Berlin</b>
Andre Gaul, Freifunk

Please also check to correct the detailed page.

**Comment by mariobehling** [comment]
Ok, think I got it. There is an additional field status in the spreadsheet. I will insert a column. Let's check if it works now.

**Comment by mananwason** [comment]
@mariobehling What activity are you talking about?

**Comment by mariobehling** [comment]
was an incompatibilty in the sheet. i fixxed it already.

**Comment by mananwason** [comment]
Oh okay !! Sorry for the late reply.
