### ISSUE TITLE
Maps Fragment not working 

### ISSUE THREAD

**Issue by mananwason** [fossasia/ots15-companion#6]
Maps stop due to authentication issue.

**Comment by championswimmer** [comment]
I'll check this out. Btw, you are trying with an app that is signed with the debug.jks key right ?

@mariobehling could you provide me the latitude and longitude of ots 15   ?

**Comment by mananwason** [comment]
@championswimmer I am working on this. I am using the key from the project you created.

**Comment by mananwason** [comment]
@championswimmer It's working with the hardcoded value. My mistake I didn't pull the changes. I am working on retrieving the map url now.
