### ISSUE TITLE
Display logo in sponsors section without changing image form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/ots15-companion#8]
The is a round shape on the edges of sponsors logos. Please display logos as in the original image.

**Comment by mananwason** [comment]
@mariobehling This is due to the scaletype I guess. I'll fix this.

**Comment by mananwason** [comment]
@mariobehling I think this is some kind of a bug with volley. I have checked everything in our code, even changed resolutions of images etc., but this doesn't seem to be solved. @batraabhishek @championswimmer  can you suggest something?

**Comment by mariobehling** [comment]
@mananwason Yes, we need to start to distinguish between test and live doc. Some sponsors were missing in the doc and this is a spreadsheet used in a live app. Please test with a test document in future. @batraabhishek @championswimmer The issue here is that the logos are roundshaped without a reason. We need the unchanged images.

**Comment by batraabhishek** [comment]
Fixed
